server:
  port: 8081
  context-path: /dangdang
  jsp-servlet:
    init-parameters:
      development: true
#数据源的连接
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ddm?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 501250
  #视图解析器的配置
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #编码格式的设置,true代表响应是使用请求的编码格式
  http:
    encoding:
      charset: utf-8
      force: true

#指定扫描的接口和mapper文件
mybatis:
  mapper-locations: com/baizhi/springboot/dao/*Mapper.xml
  type-aliases-package: com.baizhi.springboot.entity